"""add_chunking_fields_to_knowledge_base

Revision ID: c5a31eff30c8
Revises: e79e541ba92c
Create Date: 2025-04-08 22:31:47.707155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5a31eff30c8'
down_revision = 'e79e541ba92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('chunk_size', sa.Integer(), nullable=False))
    op.add_column('knowledge_bases', sa.Column('chunk_overlap', sa.Integer(), nullable=False))
    op.add_column('knowledge_bases', sa.Column('chunking_strategy', sa.String(length=50), nullable=False))
    op.alter_column('permissions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('permissions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_column('knowledge_bases', 'chunking_strategy')
    op.drop_column('knowledge_bases', 'chunk_overlap')
    op.drop_column('knowledge_bases', 'chunk_size')
    # ### end Alembic commands ###
